packages:
  - 'apps/*'
  - 'packages/*'
allowBuilds:
  '@sentry/cli': true
  browser-tabs-lock: false
  bufferutil: false
  core-js: false
  cpu-features: false
  esbuild: true
  protobufjs: false
  sharp: true
  ssh2: false
  unrs-resolver: true
  utf-8-validate: false
overrides:
  '@react-native/jest-preset>@jest/create-cache-key-function': 30.4.1
  '@react-native/jest-preset>babel-jest': 30.4.1
  '@react-native/jest-preset>jest-environment-node': 30.4.1
  'jest-expo>@jest/create-cache-key-function': 30.4.1
  'jest-expo>@jest/globals': 30.4.1
  'jest-expo>babel-jest': 30.4.1
  'jest-expo>jest-environment-jsdom': 30.4.1
  'jest-expo>jest-snapshot': 30.4.1
